### ISSUE TITLE
【BUG REPORT】load spine

### ISSUE THREAD

**Issue by YangLG-7** [pixijs/spine#415]
in my index.js，I use
`
import * as PIXI from 'pixi.js';
import { Spine } from 'pixi-spine';
`
to load spine。

but the console show 
 `Uncaught TypeError: Cannot read properties of undefined (reading 'substr')`。
I check the source  `@pixi-spine/load-uni/lib/loader-uni.es.js`

the error code is that：
`
function detectSpineVersion(version) {
    var ver3 = version.substr(0, 3);
    var verNum = Math.floor(+ver3 * 10 + 1e-3);
    if (ver3 === '3.7') {
        return SPINE_VERSION.VER37;
    }
    if (ver3 === '3.8') {
        return SPINE_VERSION.VER38;
    }
    if (ver3 === '4.0') {
        return SPINE_VERSION.VER40;
    }
    // try parse old versions with 3.7
    if (verNum < SPINE_VERSION.VER37) {
        return SPINE_VERSION.VER37;
    }
    return SPINE_VERSION.UNKNOWN;
}
`

This is my version
`
"pixi-spine": "^3.0.13",
"pixi.js": "^6.1.3"
`

This is the library I use [https://github.com/miltoncandelero/pixi-hotwire](url)

so,how can i load a spine？Thank you for your reply

**Comment by ivanpopelyshev** [comment]
That's obvious error. make a PR, change "substr" on "substring" , someone will merge it, rebuild pixi-spine and publish new version

**Comment by ivanpopelyshev** [comment]
Alternatively: just make a polyfill on substr. This function existed before: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

**Comment by ivanpopelyshev** [comment]
Actually, `Uncaught TypeError: Cannot read properties of undefined (reading 'substr')` means that there's no `version` field on your json file. Check what you are geting through the network.

**Comment by YangLG-7** [comment]
> Actually, `Uncaught TypeError: Cannot read properties of undefined (reading 'substr')` means that there's no `version` field on your json file. Check what you are geting through the network.

I think this happens when the spine file is loaded. I installed the latest version

**Comment by YangLG-7** [comment]
pixi-spine  can't recognize pixi-version

**Comment by ivanpopelyshev** [comment]
Please debug this thing. Place a breakpoint there and look whether there's "version" field in json you load.

**Comment by YangLG-7** [comment]
hi,I submitted pr

**Comment by edward677** [comment]
作者解决了这个问题吗

**Comment by ivanpopelyshev** [comment]
@kerimdragolj Its not the same issue. Please give me full reproduction. Most probably, you loaded wrong json file

**Comment by kerimdragolj** [comment]
@ivanpopelyshev yes you were correct, it was missing version, any idea why? i mean file was exported from Spine so it should be correct out of the box, containing all the needed data? After manually adding version i got rid of this error but stumbled on another one, but i guess i will just have to keep investigating these one by one... anyways thanks a lot for quick response, much appreciated!

**Comment by ivanpopelyshev** [comment]
Which version of spine is it?

**Comment by ivanpopelyshev** [comment]
Can you please make issue at https://github.com/EsotericSoftware/spine-runtimes/issues ? With description how did you get that file, how problem was solved and link to this thread?

**Comment by kerimdragolj** [comment]
@ivanpopelyshev can you please check if this exported json spine looks good to you, and if you can use it https://drive.google.com/file/d/1tKBNyPF2K_5nQXMr61DXdTRA-iQN8b3w/view?usp=sharing

**Comment by kerimdragolj** [comment]
Ahh sorry about that.. i was trying to get different output by changing version on export... but overall structure is the same either way just that 'spine' field changes.. i've reuploaded 4.1.09, you can find it [here](https://drive.google.com/file/d/1pGXpkR6jgqkPpxk9oV7bl9WaqVOQY2Gh/view?usp=sharing)

**Comment by kerimdragolj** [comment]
Nevermind it was code related issue, but still have to manually add that version field on each export...

**Comment by netherglaive** [comment]
What was the issue?? @kerimdragolj I'm running into the same thing, but I see another error with bones after adding version. 
<img width="626" alt="Screen Shot 2022-10-09 at 8 35 16 PM" src="https://user-images.githubusercontent.com/4357161/194786661-bdd69b84-6014-4e02-a189-c2a5f9c6a11e.png">

**Comment by netherglaive** [comment]
<img width="466" alt="Screen Shot 2022-10-09 at 8 52 13 PM" src="https://user-images.githubusercontent.com/4357161/194787327-81053534-0326-4167-8b3f-d76f2df97303.png">
to add more detail boneData.parent is a string and doesnt have a 'index' so parent_1 is undefined see here for uncompiled code: https://github.com/pixijs/spine/blob/master/packages/runtime-4.1/src/core/Skeleton.ts#L75

**Comment by netherglaive** [comment]
my guess here is the loader is not implemented correctly.. will try fixing that..

**Comment by netherglaive** [comment]
solved with the loader used this as an example: https://codesandbox.io/s/pixi-spine-30-test-0iopd?file=/src/index.ts

**Comment by Tousen** [comment]
![parse runtime error](https://user-images.githubusercontent.com/594259/196038786-64029c27-9453-436c-8fa9-0ab0deec4b4d.png)
Hi there! Have same problem when try to parse binary files: so some of files could return null during readString and after that runtime error it will not try to read it as 4.0 or 4.1 file, need to add some error handling for that case @ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
@badlogic Whats up with version in binary files?

**Comment by badlogic** [comment]
Nothing's up afaics https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/spine-ts/spine-core/src/SkeletonBinary.ts#L77

At a minimum, we need to know the exact Spine Editor versions the binary files have been exported from.

**Comment by ivanpopelyshev** [comment]
@Tousen give us the files please and the version.

**Comment by Tousen** [comment]
[skeleton.zip](https://github.com/pixijs/spine/files/9795101/skeleton.zip)
so steps to reproduce is just to create emty project in spine(i used latest 4.1.14) and export as binary (you can use attached one)
and it will throw error here if you'll try to load it 
https://github.com/pixijs/spine/blob/d625529c0edbbeaec7a9209ce299eff284f015d7/packages/loader-uni/src/SpineLoader.ts#L16

**Comment by Tousen** [comment]
@ivanpopelyshev pls review/comment/fixUsingOwnWay https://github.com/pixijs/spine/pull/468 , thanks)

**Comment by StreakingMan** [comment]
Is there any progress on this issue? 😭

**Comment by ivanpopelyshev** [comment]
> Is there any progress on this issue? 😭

I thought that one was fixed? Can you modify spine.js file directly for your project?

**Comment by StreakingMan** [comment]
> > Is there any progress on this issue? 😭
> 
> I thought that one was fixed? Can you modify spine.js file directly for your project?

here's my package versions:
```
        "pixi-spine": "^4.0.4",
        "pixi.js": "^7.2.4",
```

still got error `Uncaught TypeError: Cannot read properties of undefined (reading 'substr')`, and I manualy and version in spine json file it got the same error:


> What was the issue?? @kerimdragolj I'm running into the same thing, but I see another error with bones after adding version. <img alt="Screen Shot 2022-10-09 at 8 35 16 PM" width="626" src="https://user-images.githubusercontent.com/4357161/194786661-bdd69b84-6014-4e02-a189-c2a5f9c6a11e.png">

It seems SpinePhaser still not work...

> my guess here is the loader is not implemented correctly.. will try fixing that..

<details>
  <summary>some other information</summary>

my code:
```typescript
import 'pixi-spine';
import { Application, Assets } from 'pixi.js';
import { Spine } from 'pixi-spine';

const app: any = new Application();
document.body.appendChild(app.view);

Assets.load('/assets/mix-and-match-pro-json/mix-and-match-pro.json').then(
    (resource) => {
        console.log(resource);
        const animation = new Spine(resource);
        app.stage.addChild(animation);

        // add the animation to the scene and render...
        app.stage.addChild(animation);

        if (animation.state.hasAnimation('run')) {
            // run forever, little boy!
            animation.state.setAnimation(0, 'run', true);
            // dont run too fast
            animation.state.timeScale = 0.1;
            // update yourself
            animation.autoUpdate = true;
        }
    }
);
```

mix-and-match-pro.json  using spine 4.1
[mix-and-match-pro.json](https://github.com/pixijs/spine/files/13428877/mix-and-match-pro.json)

</details>

**Comment by Tousen** [comment]
> Is there any progress on this issue? 😭

the described issue was for binary files and it was fixed since 3.1.2, I think it is better to create a new one for this case with your details

**Comment by StreakingMan** [comment]
After upgrading Pixi.js to 7.3.2, everything works fine. Just ignore me.
